### ISSUE TITLE
Allow merging multiple XMLs

### ISSUE THREAD

**Issue by foursyth** [extent-framework/extentreports-dotnet-cli#6]
This question was asked on stackoverflow but I feel it would be a good addition to the cli.  

Post:  https://stackoverflow.com/questions/54901871/merge-nunit3-xmls-into-one-html-for-publishing-to-jenkins

**Comment by anshooarora** [comment]
You can track this enhancement [here](https://github.com/extent-framework/extentreports-dotnet-cli/tree/allow-merge)
