### ISSUE TITLE
Question on Useage

### ISSUE THREAD

**Issue by billkindle** [extent-framework/extentreports-dotnet-cli#8]
I've been using ReportUnit for Pester reports for about a year now. I see that ExtentReports has taken over. Am I just ignorant or is there no *.exe for this new version like there was for ReportUnit? I've read the docs but still am a little confused on how to replace ReportUnit with ExtentReports and use it.

**Comment by foursyth** [comment]
The [NuGet package](https://www.nuget.org/packages/extent) contains the `exe`.  

Usage [here](https://github.com/extent-framework/extentreports-dotnet-cli#processing-a-single-file)

**Comment by anshooarora** [comment]
The new cli is very similar to ReportUnit, except for the fact that it uses ExtentReports for contemplating and command line flags to pass args.

For the exe, I can add it to the repo if that helps. It can be downloaded from Nuget in the meantime.

**Comment by billkindle** [comment]
> 
> 
> The new cli is very similar to ReportUnit, except for the fact that it uses ExtentReports for contemplating and command line flags to pass args.
> 
> For the exe, I can add it to the repo if that helps. It can be downloaded from Nuget in the meantime.

Thank you very much for the explanation. Yes, it would be very helpful for an exe to be included in the repo. I'm a Sysadmin using the ReportUnit tool for some Pester reporting, and would like to do some testing with ExtentReports.

**Comment by jahnavi175** [comment]
@anshooarora  report unit was far better than extent report . we were able to see the test summary with number of actual test cases, whereas this extent report is giving us the test suite result, the green field represents how many test suites have passed, this is not at all helpful for us in tracking how many test cases (It statements in Pester ) have passed, please respond to my issue. Please help me find a way to know how many test cases have passed and also the steps field is not understandable .Please reply.
![er](https://user-images.githubusercontent.com/46793372/77059347-ca019d80-69fc-11ea-8742-8d24db4f7d92.PNG)

**Comment by anshooarora** [comment]
@jahnavi175 These features can be added, it would help to get more details. If you don't mind opening the relevant enhancement requests, thank you.
